from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('settings/', views.settings_view, name='settings'),
    path('settings/profile/', views.settings_profile_view, name='settings_profile'),
    path('settings/password/', views.settings_password_view, name='settings_password'),
    path('settings/gps/', views.settings_gps_view, name='settings_gps'),
    path('settings/map/', views.settings_map_view, name='settings_map'),
    path('settings/data/', views.settings_data_view, name='settings_data'),
    path('settings/about/', views.settings_about_view, name='settings_about'),
    path('settings/export/', views.export_user_data, name='export_user_data'),
    path('post/create/', views.create_post, name='create_post'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/comment/', views.add_comment, name='add_comment'),
    path('post/<int:pk>/comment/<int:comment_id>/like/', views.toggle_comment_like, name='toggle_comment_like'),
    path('post/<int:pk>/comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
    path('post/<int:pk>/like/', views.toggle_like, name='toggle_like'),
    path('my-posts/', views.my_posts, name='my_posts'),
    path('profile/<str:username>/', views.user_profile_view, name='user_profile'),
    path('profile/<str:username>/follow/', views.toggle_follow, name='toggle_follow'),
    path('search/', views.search_view, name='search'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('notifications/<int:pk>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/<int:pk>/delete/', views.delete_notification, name='delete_notification'),
    path('notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('api/posts/', views.api_posts, name='api_posts'),
    path('api/users/search/', views.user_search_api, name='user_search_api'),
    path('api/profile/<str:username>/footprint/', views.user_footprint_api, name='user_footprint_api'),
    path('api/profile/<str:username>/badges/', views.user_badges_api, name='user_badges_api'),
    path('auth/google/login/', views.google_login, name='google_login'),
    path('auth/google/callback/', views.google_callback, name='google_callback'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
]
