# Generated by Django 6.0.6 on 2026-08-27 07:14

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='รูปภาพการเดินทาง')),
                ('caption', models.TextField(help_text='บอกเล่าประสบการณ์ ความประทับใจ หรือสิ่งที่น่าสนใจในสถานที่นี้', verbose_name='แคปชั่น / รายละเอียดการเดินทาง')),
                ('location_name', models.CharField(blank=True, help_text='เช่น ดอยอินทนนท์, คาเฟ่ริมหาดพัทยา หรือชื่อสถานที่ที่ตรวจพบ', max_length=255, null=True, verbose_name='ชื่อสถานที่ / จุดเช็คอิน')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ละติจูด (Latitude)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='ลองจิจูด (Longitude)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='ผู้โพสต์')),
            ],
            options={
                'verbose_name': 'โพสต์เช็คอิน',
                'verbose_name_plural': 'โพสต์เช็คอินทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
    ]
