# Generated by Django 6.0.6 on 2026-08-30 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_post_likes_post_views_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='เช่น คาเฟ่, ภูเขา, ทะเล, จุดชมวิว, พิกัดลับ', max_length=255, null=True, verbose_name='แท็ก / หมวดหมู่'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='ข้อความความคิดเห็น')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาแสดงความคิดเห็น')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='checkin.post', verbose_name='โพสต์')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แสดงความคิดเห็น')),
            ],
            options={
                'verbose_name': 'ความคิดเห็น',
                'verbose_name_plural': 'ความคิดเห็นทั้งหมด',
                'ordering': ['created_at'],
            },
        ),
    ]
