# Generated by Django 6.0.6 on 2026-08-30 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_post_tags_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='ชื่อที่ต้องการให้คนอื่นเห็นในโพสต์และคอมเมนต์', max_length=100, null=True, verbose_name='ชื่อที่แสดง (Display Name)')),
                ('bio', models.TextField(blank=True, help_text='แนะนำตัวเอง สไตล์การท่องเที่ยว หรือคำคมที่ชอบ', max_length=500, null=True, verbose_name='ประวัติโดยย่อ (Bio)')),
                ('avatar_color', models.CharField(default='from-emerald-500 to-teal-400', max_length=50, verbose_name='ธีมสีอวาตาร์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน')),
            ],
        ),
    ]
