# Generated by Django 6.0.6 on 2026-08-30 19:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='รูปภาพโปรไฟล์'),
        ),
    ]
