# Generated by Django 6.0.6 on 2026-08-30 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_profile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('like_post', 'ถูกใจโพสต์'), ('like_comment', 'ถูกใจความคิดเห็น'), ('comment_post', 'แสดงความคิดเห็น')], max_length=50, verbose_name='ประเภทการกระทำ')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาแจ้งเตือน')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_made', to=settings.AUTH_USER_MODEL, verbose_name='ผู้กระทำ')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='checkin.comment', verbose_name='ความคิดเห็นที่เกี่ยวข้อง')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='checkin.post', verbose_name='โพสต์ที่เกี่ยวข้อง')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับการแจ้งเตือน')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือนทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
    ]
