# Generated by Django 6.0.6 on 2026-08-31 02:56

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='รูปภาพ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับการแสดงผล')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='checkin.post', verbose_name='โพสต์')),
            ],
            options={
                'verbose_name': 'รูปภาพโพสต์',
                'verbose_name_plural': 'รูปภาพโพสต์ทั้งหมด',
                'ordering': ['order', 'id'],
            },
        ),
    ]
