# Generated by Django 6.0.6 on 2026-08-31 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_postimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like_post', 'ถูกใจโพสต์'), ('like_comment', 'ถูกใจความคิดเห็น'), ('comment_post', 'แสดงความคิดเห็น'), ('follow_user', 'เริ่มติดตามคุณ')], max_length=50, verbose_name='ประเภทการกระทำ'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่ติดตาม')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL, verbose_name='ผู้กดติดตาม')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ถูกติดตาม')),
            ],
            options={
                'verbose_name': 'การติดตาม',
                'verbose_name_plural': 'การติดตามทั้งหมด',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
