# Generated by Django 6.0.7 on 2026-09-01 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkin", "0009_alter_notification_verb_follow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="ซ่อนความคิดเห็น"),
        ),
        migrations.AddField(
            model_name="post",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="ซ่อนโพสต์"),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_banned",
            field=models.BooleanField(
                default=False,
                help_text="หากเปิดใช้งาน ผู้ใช้จะไม่สามารถเข้าสู่ระบบหรือใช้งานระบบได้",
                verbose_name="ถูกระงับ/แบนบัญชี",
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "ขยะ / สแปม (Spam)"),
                            ("inappropriate", "เนื้อหาไม่เหมาะสม / ลามกอนาจาร"),
                            ("harassment", "การคุกคาม / ความเกลียดชัง"),
                            ("fake_news", "ข้อมูลเท็จ / หลอกลวง"),
                            ("rules_violation", "ละเมิดกฎชุมชน"),
                            ("other", "อื่นๆ"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="เหตุผลในการรายงาน",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, null=True, verbose_name="รายละเอียดเพิ่มเติม"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอการตรวจสอบ"),
                            ("resolved", "ดำเนินการเรียบร้อย (ซ่อน/ลบ)"),
                            ("dismissed", "ปฏิเสธรายงาน"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="สถานะรายงาน",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="เวลาที่รายงาน"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="เวลาที่อัปเดต"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="checkin.comment",
                        verbose_name="ความคิดเห็นที่ถูกรายงาน",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="checkin.post",
                        verbose_name="โพสต์ที่ถูกรายงาน",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้รายงาน",
                    ),
                ),
            ],
            options={
                "verbose_name": "การรายงาน",
                "verbose_name_plural": "การรายงานทั้งหมด",
                "ordering": ["-created_at"],
            },
        ),
    ]
