# Generated by Django 6.1 on 2026-09-01 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0009_alter_notification_verb_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ร่วมทริปที่ถูกแท็ก'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like_post', 'ถูกใจโพสต์'), ('like_comment', 'ถูกใจความคิดเห็น'), ('comment_post', 'แสดงความคิดเห็น'), ('follow_user', 'เริ่มติดตามคุณ'), ('post_tagged', 'แท็กคุณในโพสต์ทริป')], max_length=50, verbose_name='ประเภทการกระทำ'),
        ),
    ]
