# Generated by Django 6.1 on 2026-09-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0010_post_tagged_users_alter_notification_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='ซ่อนโพสต์'),
        ),
    ]
