# Generated by Django 6.1 on 2026-09-01 12:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0010_comment_is_hidden_post_is_hidden_profile_is_banned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='คะแนนรีวิวเฉลี่ย'),
        ),
        migrations.AddField(
            model_name='post',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนรีวิวทั้งหมด'),
        ),
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='คะแนนรวม (1-5 ดาว)')),
                ('aspect_scenery', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='คะแนนด้านบรรยากาศ/วิว')),
                ('aspect_transport', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='คะแนนด้านความสะดวกในการเดินทาง')),
                ('review_text', models.TextField(blank=True, null=True, verbose_name='ข้อความรีวิว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='checkin.post', verbose_name='โพสต์/สถานที่ที่ถูกรีวิว')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_reviews', to=settings.AUTH_USER_MODEL, verbose_name='ผู้เขียนรีวิว')),
            ],
            options={
                'verbose_name': 'รีวิวสถานที่',
                'verbose_name_plural': 'รีวิวสถานที่ทั้งหมด',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post'], name='checkin_pla_post_id_b19774_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
