# Generated by Django 6.1 on 2026-09-01 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0011_post_avg_rating_post_review_count_placereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัสเหรียญ')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อเหรียญรางวัล')),
                ('description', models.TextField(verbose_name='คำอธิบายเงื่อนไข')),
                ('icon', models.CharField(max_length=255, verbose_name='ไอคอน/สัญลักษณ์')),
                ('criteria_type', models.CharField(choices=[('PROVINCE_COUNT', 'จำนวนจังหวัดที่พิชิต'), ('TAG_COUNT', 'จำนวนโพสต์ในหมวดหมู่/แท็ก'), ('TIME_RANGE', 'ช่วงเวลาโพสต์ (เช้า/ดึก)'), ('POST_COUNT', 'จำนวนโพสต์รวม')], max_length=50, verbose_name='ประเภทเงื่อนไข')),
                ('criteria_config', models.JSONField(blank=True, default=dict, verbose_name='การตั้งค่าเงื่อนไข (JSON)')),
            ],
            options={
                'verbose_name': 'เหรียญรางวัล',
                'verbose_name_plural': 'เหรียญรางวัลทั้งหมด',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=100, unique=True, verbose_name='ชื่อจังหวัด (ไทย)')),
                ('name_en', models.CharField(max_length=100, unique=True, verbose_name='ชื่อจังหวัด (อังกฤษ)')),
                ('svg_id', models.CharField(max_length=50, unique=True, verbose_name='SVG Element ID')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='ภูมิภาค')),
            ],
            options={
                'verbose_name': 'จังหวัด',
                'verbose_name_plural': 'จังหวัดทั้งหมด',
                'ordering': ['name_th'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ร่วมทริปที่ถูกแท็ก'),
        ),
        migrations.AddField(
            model_name='post',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='checkin.province', verbose_name='จังหวัด'),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ได้รับ')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='checkin.badge', verbose_name='เหรียญรางวัล')),
                ('related_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_badges', to='checkin.post', verbose_name='โพสต์ที่จุดชนวน')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ได้รับเหรียญ')),
            ],
            options={
                'verbose_name': 'เหรียญรางวัลของผู้ใช้',
                'verbose_name_plural': 'เหรียญรางวัลของผู้ใช้ทั้งหมด',
                'ordering': ['-awarded_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like_post', 'ถูกใจโพสต์'), ('like_comment', 'ถูกใจความคิดเห็น'), ('comment_post', 'แสดงความคิดเห็น'), ('follow_user', 'เริ่มติดตามคุณ'), ('post_tagged', 'แท็กคุณในโพสต์ทริป'), ('badge_unlocked', 'ปลดล็อกเหรียญรางวัล')], max_length=50, verbose_name='ประเภทการกระทำ'),
        ),
    ]
