# Generated by Django 6.1 on 2026-09-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0011_post_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avg_rating',
            field=models.FloatField(default=0.0, verbose_name='คะแนนเฉลี่ย (1-5 ดาว)'),
        ),
        migrations.AddField(
            model_name='post',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนรีวิว'),
        ),
    ]
