# Generated by Django 6.0.6 on 2026-09-01 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0013_report_reported_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='อีเมลที่ส่งรหัส')),
                ('otp_code', models.CharField(max_length=6, verbose_name='รหัส OTP 6 หลัก')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('is_used', models.BooleanField(default=False, verbose_name='ถูกใช้งานแล้ว')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_otps', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'รหัสยืนยันรีเซ็ตรหัสผ่าน (OTP)',
                'verbose_name_plural': 'รหัสยืนยันรีเซ็ตรหัสผ่าน (OTP) ทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
    ]
