# Generated by Django 6.0.6 on 2026-09-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0014_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='จำนวนครั้งที่กรอกผิด'),
        ),
    ]
