# Generated by Django 6.1 on 2026-09-01 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkin', '0009_alter_notification_verb_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='ชื่อคอลเลกชัน/ทริป')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('is_public', models.BooleanField(default=False, verbose_name='เปิดเป็นสาธารณะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของคอลเลกชัน')),
            ],
            options={
                'verbose_name': 'คอลเลกชันทริป',
                'verbose_name_plural': 'คอลเลกชันทริปทั้งหมด',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='บันทึกเมื่อ')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='checkin.post', verbose_name='โพสต์ที่บันทึก')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='planner.collection', verbose_name='คอลเลกชัน/ทริป')),
            ],
            options={
                'verbose_name': 'โพสต์ที่บันทึก',
                'verbose_name_plural': 'โพสต์ที่บันทึกทั้งหมด',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'collection'], name='planner_boo_user_id_059634_idx')],
                'unique_together': {('user', 'post', 'collection')},
            },
        ),
    ]
