# Generated by Django 6.1 on 2026-09-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='collection_covers/', verbose_name='รูปปกคอลเลกชัน'),
        ),
    ]
